version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  app:
    build: .
    container_name: node_app
    ports:
      - "3009:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: test
      DB_PORT: 5432
    networks:
      - app_network
    volumes:
      - ~/wapix-data/wwebjs_auth:/app/.wwebjs_auth
      - ~/wapix-data/wwebjs_cache:/app/.wwebjs_cache

volumes:
  postgres_data:
  wapix_data:

networks:
  app_network:
